services:
  # Backend API
  - type: web
    name: joinnexora-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: https://joinnexora-frontend.onrender.com
      - key: VITE_API_URL
        value: https://joinnexora-backend.onrender.com

  # Frontend Static Site
  - type: web
    name: joinnexora-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://joinnexora-backend.onrender.com 